Repository OGJG-ZAMONG/ZAMONG_Frontend_V1, pull requests merged in 2021-10, with the labels that each got.

#58 23 Chat UI
  zamong/src/assets/icon/edit-grey.svg
  zamong/src/assets/icon/search.svg
  zamong/src/assets/icon/send.svg
  zamong/src/assets/index.ts
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/ChatBalloon/My/MyText.tsx
  zamong/src/components/Chat/ChatBalloon/Opponent/OpponentText.tsx
  zamong/src/components/Chat/ChatRoom/ChatRoom.tsx
  zamong/src/components/Chat/ChatRoom/styles.ts
  zamong/src/components/Chat/styles.ts
  zamong/src/container/Chat/ChatContainer.tsx
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#64 62 Footer Restyle
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/Footer/Footer.tsx
  zamong/src/components/Footer/styles.ts
  zamong/src/components/MainPage/FollowList/FollowList.tsx
Labels: bug

#71 63 Add Navigation Header
  zamong/src/assets/icons/Chat.svg
  zamong/src/assets/icons/Coin.svg
  zamong/src/assets/icons/Discovery.svg
  zamong/src/assets/icons/ShoppingCart.svg
  zamong/src/components/Header/Header.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginComponent/index.ts
  zamong/src/components/Header/NonLoginComponent/NonLoginComponent.tsx
  zamong/src/components/Header/NonLoginComponent/index.ts
  zamong/src/components/Header/NonLoginComponent/styles.ts
  zamong/src/components/Header/styles.ts
Labels: enhancement

#74 73 Change Dream Write Header Footer Structure
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/container/DiaryWrite/index.tsx
Labels: enhancement

#76 72 Sell Dream Write UI
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/SellWrite/SellWrite.tsx
  zamong/src/components/SellWrite/component/InputPrice/InputPrice.tsx
  zamong/src/components/SellWrite/component/InputPrice/styles.ts
  zamong/src/components/SellWrite/styles.ts
  zamong/src/container/SellWrite/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#77 :bug: :: (#54) Rename file
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/SignUp/SignUpND/SignUp.tsx
  zamong/src/components/SignUp/SignUpST/SignUp.tsx
  zamong/src/components/SignUp/SingUpRD/SignUp.tsx
Labels: bug

#78 66 Set Api Default
  zamong/src/utils/api/default/index.ts
  zamong/src/utils/axios/index.ts
Labels: documentation

#97 94 Dream Diary Style
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/styles.ts
Labels: enhancement

#100 86 Dream Diary Write Adding picture Implemented
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
Labels: enhancement

#107 106 AuthBackground Style
  zamong/src/common/auth/style.ts
  zamong/src/style/color.ts
Labels: enhancement

#110 109 Add .env in .gitignore
  zamong/.gitignore
Labels: documentation

#119 118 AuthBackground Style
  zamong/src/components/Common/auth/styles.ts
Labels: enhancement
