Repository OGJG-ZAMONG/ZAMONG_Frontend_V1, pull requests merged in 2021-11, with the labels that each got.

#149 Diary Detail
  package-lock.json
  zamong/src/assets/icons/disLike.svg
  zamong/src/assets/icons/github.svg
  zamong/src/assets/icons/lightDisLike.svg
  zamong/src/assets/icons/lightLike.svg
  zamong/src/assets/icons/like.svg
  zamong/src/assets/icons/link.svg
  zamong/src/assets/icons/minus.svg
  zamong/src/assets/icons/more.svg
  zamong/src/assets/icons/plus.svg
  zamong/src/assets/icons/testProfile.svg
  zamong/src/assets/icons/toggle.svg
  zamong/src/assets/index.ts
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/Recommend.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/styles.ts
  zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/ReplyComment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/styles.ts
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/components/DiaryDetail/Comment/styles.ts
  zamong/src/components/DiaryDetail/DiaryDetail.tsx
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/DiaryDetail/Posting/styles.ts
  zamong/src/components/DiaryDetail/styles.ts
  zamong/src/components/Footer/Footer.tsx
  zamong/src/components/Header/Filter/Filter.tsx
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/SignUp/SignUpND/styles.ts
  zamong/src/container/DiaryDetail/index.tsx
  zamong/src/container/Login/index.tsx
  zamong/src/container/MainPage/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#147 146 Profile Page Style
  zamong/src/components/Profile/style.ts
Labels: enhancement

#151 150 Take measures right away
  zamong/src/components/MainPage/MainPage.tsx
  zamong/src/components/SignUp/SignUpND/styles.ts
  zamong/src/container/MainPage/index.tsx
Labels: bug

#152 83 Login Api
  zamong/src/components/Login/Login.tsx
  zamong/src/constance/uri.ts
  zamong/src/utils/api/Login/index.ts
  zamong/src/utils/api/default/index.ts
Labels: enhancement

#162 161 Dream detail get api
  zamong/src/models/dto/response/dreamDetailResponse.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#166 127 Write dream API
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/components/DiaryWrite/component/ElapsedTime/ElapsedTime.tsx
  zamong/src/components/DiaryWrite/component/Picker/DatePicker/DatePicker.tsx
  zamong/src/components/DiaryWrite/component/Picker/TimePicker/TimePicker.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Content/Content.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/DreamType.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Header/Header.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamDate/DreamDate.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/DreamQuality.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/ItemContent/ItemContent.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamTime/Content/Content.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamTime/DreamTime.tsx
  zamong/src/components/DiaryWrite/component/styles.ts
  zamong/src/components/DiaryWrite/model.ts
  zamong/src/components/FileInput/FileInput.tsx
  zamong/src/components/FileInput/styles.ts
  zamong/src/components/SellWrite/SellWrite.tsx
  zamong/src/constance/dreamQualitys.ts
  zamong/src/constance/dreamType.ts
  zamong/src/constance/uri.ts
  zamong/src/container/DiaryWrite/index.tsx
  zamong/src/interface/Code/index.ts
  zamong/src/interface/Time/index.ts
  zamong/src/models/dto/request/diaryWriteRequest.ts
  zamong/src/models/dto/response/diaryWriteResponse.ts
  zamong/src/models/dto/response/dreamDetailResponse.ts
  zamong/src/utils/api/DiaryWrite/index.ts
  zamong/src/utils/api/DreamDetail/index.ts
  zamong/src/utils/api/default/index.ts
Labels: enhancement

#173 172 Change Diary Wirte Inner Component style or function
  zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Content/Content.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Header/Header.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/styles.ts
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/DreamQuality.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/ItemContent/ItemContent.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/Selecter/Selecter.tsx
Labels: enhancement

#175 174 Fix Save Time
  zamong/src/components/DiaryWrite/component/ElapsedTime/ElapsedTime.tsx
Labels: bug

#177 176 Rename File name
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamList/DreamList.tsx
  zamong/src/components/MainPage/FollowList/styles.ts
  zamong/src/components/MainPage/globalstyle.ts
  zamong/src/components/MainPage/styles.ts
Labels: documentation

#183 178 Implementation slider functional
  zamong/src/components/MainPage/Slider/Slider.tsx
  zamong/src/components/MainPage/Slider/styles.ts
Labels: enhancement

#184 159 Profile api
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/constance/uri.ts
  zamong/src/container/Profile/index.tsx
  zamong/src/models/dto/response/myProfileResponse.ts
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#189 169 Main Page API
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Header/Filter/Filter.tsx
  zamong/src/components/Header/Filter/styles.ts
  zamong/src/components/Header/Header.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginComponent/styles.ts
  zamong/src/components/Header/NonLoginComponent/NonLoginComponent.tsx
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/constance/uri.ts
  zamong/src/container/Profile/index.tsx
  zamong/src/models/dto/request/shareDreamRequest.ts
  zamong/src/models/dto/response/myProfileResponse.ts
  zamong/src/models/dto/response/shareDreamResponse.ts
  zamong/src/utils/api/Main/index.ts
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#190 181 Integrated assets folder
  zamong/package-lock.json
  zamong/src/assets/icons/downChevron.svg
  zamong/src/assets/icons/edit-grey.svg
  zamong/src/assets/icons/edit.svg
  zamong/src/assets/icons/filterIcon.svg
  zamong/src/assets/icons/lockOpen.svg
  zamong/src/assets/icons/pointer.svg
  zamong/src/assets/icons/search.svg
  zamong/src/assets/icons/searchIcon.svg
  zamong/src/assets/icons/secure.svg
  zamong/src/assets/icons/send.svg
  zamong/src/assets/index.ts
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
  zamong/src/components/Header/Header.tsx
  zamong/yarn.lock
Labels: documentation

#192 191 Deploy S3 Action
  .github/workflows/zamong.yml
Labels: enhancement

#193 169 Main Page API
  zamong/src/models/dto/request/myShareDreamRequest.ts
  zamong/src/utils/api/Main/index.ts
Labels: enhancement

#196 195 additional main page api
  zamong/src/constance/uri.ts
  zamong/src/models/dto/response/followerResponse.ts
  zamong/src/utils/api/Main/index.ts
Labels: enhancement

#197 164 Automatic issuance of access tokens
  zamong/src/components/Login/Login.tsx
  zamong/src/constance/uri.ts
  zamong/src/utils/api/Login/index.ts
  zamong/src/utils/api/SignUp/index.ts
  zamong/src/utils/api/axios/index.ts
  zamong/src/utils/api/refresh.ts
  zamong/src/utils/axios/index.ts
Labels: enhancement

#199 Login Enter
  zamong/src/components/Login/Login.tsx
Labels: enhancement

#200 185 Profile Under(1) api
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/constance/uri.ts
  zamong/src/models/dto/response/myProfileResponse.ts
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#201 167 Implementation Functional Main Page
  zamong/src/assets/icons/lock.svg
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Dream/Dream.tsx
  zamong/src/components/Header/Filter/Filter.tsx
  zamong/src/components/Header/Filter/styles.ts
  zamong/src/components/Header/Header.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginComponent/styles.ts
  zamong/src/components/Header/NonLoginComponent/NonLoginComponent.tsx
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamList/DreamList.tsx
  zamong/src/components/MainPage/DreamList/styles.ts
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/MainPage/MainPage.tsx
  zamong/src/components/MainPage/styles.ts
  zamong/src/constance/uri.ts
  zamong/src/models/dto/request/shareDreamRequest.ts
  zamong/src/models/dto/request/shareDreamWithSortRequest.ts
  zamong/src/models/dto/response/dreamListResponse.ts
  zamong/src/models/dto/response/followingsResponse.ts
  zamong/src/models/dto/response/shareDreamResponse.ts
  zamong/src/utils/api/Main/index.ts
Labels: enhancement

#202 182 Diary Written Today Api Connection
  zamong/src/assets/icons/Checked.png
  zamong/src/assets/icons/Checked.svg
  zamong/src/assets/icons/edit.svg
  zamong/src/assets/icons/lockOpen.svg
  zamong/src/assets/icons/locked.svg
  zamong/src/assets/index.ts
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
  zamong/src/components/CardDream/MyDreamDiary/styles.ts
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Diary/Calendar/Calendar.tsx
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
  zamong/src/components/Diary/DiaryTitle/DiaryTitle.tsx
  zamong/src/components/Diary/DiaryTitle/styles.ts
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/utils/api/Diary/Calendar/index.ts
  zamong/src/utils/api/Diary/MyDreams/index.ts
  zamong/src/utils/api/calendar/index.ts
Labels: enhancement

#207 164 Fix expireAt type
  zamong/src/utils/api/Login/index.ts
  zamong/src/utils/api/refresh.ts
Labels: bug

#206 205 Fix My recent dream diary list size bug
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
Labels: bug

#209 208 Fix Refresh Function
  zamong/src/utils/api/Login/index.ts
  zamong/src/utils/api/refresh.ts
Labels: bug, enhancement

#210 168 Implementation Functional Header
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginComponent/styles.ts
Labels: enhancement

#212 Feature/204 dream sell main api connection
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Sell/Main/SellMain.tsx
  zamong/src/components/Sell/Main/styles.ts
  zamong/src/components/Sell/SellingDream/SellingDream.tsx
  zamong/src/components/Sell/SellingDream/styles.ts
  zamong/src/utils/api/Sell/Main/index.ts
Labels: enhancement

#215 213 Write Sell Dream API
  zamong/src/constance/uri.ts
  zamong/src/models/dto/request/sellWriteResquest.ts
  zamong/src/utils/api/SellWrite/index.ts
Labels: enhancement

#220 218 get Sell Dream Detail API
  zamong/src/models/dto/response/sellDreamDetailResponse.tsx
  zamong/src/utils/api/Sell/Main/index.ts
Labels: enhancement

#227 226 Change posting image uri
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/constance/uri.ts
  zamong/src/utils/api/DiaryWrite/index.ts
  zamong/src/utils/api/DreamPosting/index.ts
Labels: enhancement

#222 221 Change instance to request
  zamong/src/utils/api/Login/index.ts
  zamong/src/utils/api/SignUp/index.ts
  zamong/src/utils/api/refresh.ts
Labels: bug

#229 228 sell dream put API
  zamong/src/components/SellWrite/SellWrite.tsx
  zamong/src/utils/api/SellWrite/index.ts
Labels: enhancement

#232 211 Main Page Share Dream API
  zamong/src/utils/api/Main/index.ts
Labels: bug, enhancement

#231 214 Write Sell Dream Functional implementation
  zamong/src/components/DiaryWrite/component/styles.ts
  zamong/src/components/SellWrite/SellWrite.tsx
  zamong/src/components/SellWrite/component/InputPrice/Content/Content.tsx
  zamong/src/components/SellWrite/component/InputPrice/InputPrice.tsx
  zamong/src/container/SellWrite/index.tsx
  zamong/src/models/dto/response/sellDreamDetailResponse.tsx
  zamong/src/utils/api/Sell/Main/index.ts
  zamong/src/utils/api/SellWrite/index.ts
Labels: enhancement

#234 223 Reactive header implementation.
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginComponent/styles.ts
  zamong/src/components/Header/styles.ts
Labels: enhancement

#235 225 My Dream Style Changes
  zamong/src/components/Diary/Calendar/Calendar.tsx
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
  zamong/src/utils/api/Diary/MyDreams/index.ts
Labels: enhancement

#241 154 Post Normal Comment
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/Recommend.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/ReplyComment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/ReplyComment/styles.ts
  zamong/src/constance/uri.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#243 242 Fix Recommend component type error
  zamong/src/components/DiaryDetail/Comment/CommentBox/Recommend/Recommend.tsx
Labels: bug

#244 238 Delete Dream Buy Nav
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
Labels: enhancement

#245 160 Main page size bug
  zamong/src/components/MainPage/styles.ts
Labels: bug

#246 186 Profile Under(2) api
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Account/style.ts
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#247 237 Dream Diary Api Changes
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
  zamong/src/utils/api/Diary/MyDreams/index.ts
Labels: enhancement

#249 248 master error 고치기
  zamong/package-lock.json
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#255 250 Slider Arrow disable
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/components/MainPage/Slider/Slider.tsx
  zamong/src/components/MainPage/Slider/styles.ts
Labels: enhancement

#257 256 Fix get My diary
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/models/dto/request/myDiaryRequest.ts
  zamong/src/utils/api/Main/index.ts
Labels: bug

#258 254 Accordion Menu header click
  zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/styles.ts
Labels: enhancement

#260 253 Picker scroll reverse
  zamong/src/components/DiaryWrite/component/Picker/PickerColunm/PickerColumn.tsx
  zamong/src/components/DiaryWrite/component/Picker/PickerColunm/styles.ts
Labels: enhancement

#259 236 Joy Api Instance
  zamong/src/components/Diary/Calendar/Calendar.tsx
  zamong/src/components/Sell/Main/SellMain.tsx
  zamong/src/components/Sell/SellingDream/SellingDream.tsx
  zamong/src/utils/api/Diary/Calendar/index.ts
  zamong/src/utils/api/Sell/Main/index.ts
Labels: enhancement

#266 262 on router change header blink
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginSkeleton/LoginSkeleton.tsx
  zamong/src/components/Header/LoginSkeleton/styles.ts
Labels: enhancement

#268 265 make skeleton
  zamong/src/components/CardSkeleton/CardSkeleton.tsx
  zamong/src/components/CardSkeleton/styles.ts
  zamong/src/components/ListSkeleton/ListSkeleton.tsx
  zamong/src/components/ListSkeleton/styles.ts
Labels: enhancement

#272 271 change request to axios instance
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/MainPage/MainPage.tsx
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/utils/api/DiaryWrite/index.ts
  zamong/src/utils/api/DreamDetail/index.ts
  zamong/src/utils/api/Main/index.ts
  zamong/src/utils/api/Profile/index.ts
  zamong/src/utils/api/default/index.ts
Labels: enhancement

#269 267 on login then Diary Write
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/MainPage/MainPage.tsx
Labels: enhancement

#274 273 change axios instance login
  zamong/src/components/Header/Header.tsx
  zamong/src/components/MainPage/MainPage.tsx
  zamong/src/utils/api/refresh.ts
Labels: bug, enhancement

#276 239 Filter deactive when click Another place
  zamong/src/components/Header/Filter/Filter.tsx
Labels: enhancement

#277 216 add Shadow in filter
  zamong/src/components/Header/Filter/styles.ts
Labels: enhancement

#279 263 Link to Detail
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Sell/SellingDream/SellingDream.tsx
  zamong/src/components/Sell/SellingDream/styles.ts
Labels: enhancement

#281 280 Dream Sell Smooth Scroll Change
  zamong/src/components/Sell/Main/SellMain.tsx
Labels: enhancement

#283 180 Fix picker bug
  zamong/src/components/DiaryWrite/component/Picker/DatePicker/DatePicker.tsx
  zamong/src/components/DiaryWrite/component/Picker/Modal/Modal.tsx
  zamong/src/components/DiaryWrite/component/Picker/PickerColunm/PickerColumn.tsx
  zamong/src/components/DiaryWrite/component/Picker/TimePicker/TimePicker.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamDate/DreamDate.tsx
Labels: bug

#286 284 Change Follow and etc API Call
  zamong/src/utils/api/Main/index.ts
Labels: bug

#292 291 Change Server URL
  zamong/src/utils/api/axios/index.ts
  zamong/src/utils/api/default/index.ts
Labels: enhancement

#295 294 SignUp Cursor pointer
  zamong/src/components/SignUp/SignUpND/styles.ts
  zamong/src/components/SignUp/SignUpST/styles.ts
  zamong/src/components/SignUp/SingUpRD/styles.ts
Labels: enhancement

#293 251 Link the post
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/DiaryDetail.tsx
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/DiaryDetail/Posting/styles.ts
  zamong/src/constance/uri.ts
  zamong/src/models/dto/response/dreamDetailResponse.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#298 297 Router Change ScrollTop
  zamong/public/index.html
  zamong/src/components/Header/Header.tsx
Labels: enhancement

#299 297 Router Change ScrollTop
  zamong/src/components/CardDream/MyDreamDiary/MyDreamDiary.tsx
Labels: enhancement

#300 251 Link the post
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#302 Feature/301 refactor dream sell component
  zamong/src/components/Diary/Calendar/Calendar.tsx
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/styles.ts
  zamong/src/components/Sell/Main/SellMain.tsx
  zamong/src/components/Sell/Main/styles.ts
  zamong/src/components/Sell/SellingDream/SellingDream.tsx
  zamong/src/components/Sell/SellingDream/styles.ts
Labels: enhancement

#303 290 fix accordion header click bug
  zamong/src/components/DiaryWrite/component/Properties/Accordion/Accordion/Accordion.tsx
Labels: bug, enhancement

#309 158 Find Password UI
  zamong/src/components/FileInput/FileInput.tsx
  zamong/src/components/FileInput/styles.ts
  zamong/src/components/FindPassword/Change/Change.tsx
  zamong/src/components/FindPassword/Change/styles.ts
  zamong/src/components/FindPassword/Find/Find.tsx
  zamong/src/components/FindPassword/Find/styles.ts
  zamong/src/components/FindPassword/FindPassword.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/container/FIndPassword/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#307 148 Search Page UI
  zamong/src/components/Dream/Dream.tsx
  zamong/src/components/Search/Dream/Dream.tsx
  zamong/src/components/Search/Dream/style.ts
  zamong/src/components/Search/SearchPage.tsx
  zamong/src/components/Search/style.ts
  zamong/src/container/Search/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#311 148 Search Page UI
  zamong/src/components/Search/style.ts
Labels: enhancement

#310 305 Optimization css
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Dream/styles.ts
  zamong/src/components/Header/styles.ts
  zamong/src/components/MainPage/MainPage.tsx
Labels: enhancement

#318 186 Profile Under(2) api
  zamong/src/components/FileInput/FileInput.tsx
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Account/style.ts
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/constance/uri.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#320 252 Add comment, post more
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/components/DiaryDetail/Comment/styles.ts
  zamong/src/components/DiaryDetail/DiaryDetail.tsx
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/DiaryDetail/Posting/styles.ts
  zamong/src/components/PopupMenu/PopupMenu.tsx
  zamong/src/components/PopupMenu/styled.ts
  zamong/src/constance/uri.ts
  zamong/src/interface/PopupContent/index.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#322 312 interpretation of a dream main page publishing
  zamong/src/components/CardDream/DefaultDreamInterpretationCard/DefaultDreamInterpretationCard.tsx
  zamong/src/components/CardDream/DefaultDreamInterpretationCard/styles.ts
  zamong/src/components/CardDream/index.ts
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/components/Dream/DreamInterpretation/styles.ts
  zamong/src/components/DreamInterpretationMain/DefaultDreamInterpretation/DefaultDreamInterpretation.tsx
  zamong/src/components/DreamInterpretationMain/DefaultDreamInterpretation/styles.ts
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/styles.ts
  zamong/src/components/DreamInterpretationMain/DreamInterpretationMain.tsx
  zamong/src/components/DreamInterpretationMain/styles.ts
  zamong/src/components/MainPage/Slider/Slider.tsx
  zamong/src/components/MainPage/Slider/styles.ts
  zamong/src/constance/defaultDreamInterpretations.ts
  zamong/src/container/DreamInterpretationMain/index.tsx
  zamong/src/container/index.ts
  zamong/src/interface/DefaultDreamInterpretationType/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement
