Repository OGJG-ZAMONG/ZAMONG_Frontend_V1, pull requests merged in 2021-12, with the labels that each got.

#326 325 Fix Calendar
  zamong/src/components/Diary/Calendar/Calendar.tsx
Labels: enhancement

#327 314 interpretation of a dream main page API
  zamong/src/components/CardDream/index.ts
  zamong/src/constance/uri.ts
  zamong/src/utils/api/DreamInterpretationMain/index.ts
Labels: enhancement

#324 282 Chat Implementation
  zamong/package-lock.json
  zamong/package.json
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/ChatRoom/ChatRoom.tsx
  zamong/src/components/Chat/ChatRoom/styles.ts
  zamong/src/components/Chat/styles.ts
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
  zamong/src/utils/api/Chat/index.ts
Labels: enhancement

#329 328 fix follow uri none
  zamong/src/constance/uri.ts
Labels: bug

#331 330 Fix Diary Card style
  zamong/src/components/CardDream/FollowDreamDiary/styles.ts
  zamong/src/components/CardDream/MyDreamDiary/styles.ts
  zamong/src/components/CardDream/index.ts
Labels: bug

#335 330 Fix Diary Card style
  zamong/src/components/Diary/DiaryList/styles.ts
Labels: bug

#336 194 Add link in Main Page
  zamong/src/components/Dream/Dream.tsx
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/components/Dream/styles.ts
Labels: enhancement

#340 296 fix filter close bug
  zamong/src/components/Header/Filter/Filter.tsx
  zamong/src/components/Header/Filter/FilterContent/FilterContent.tsx
  zamong/src/components/Header/Filter/FilterContent/styles.ts
  zamong/src/components/Header/Filter/styles.ts
  zamong/src/interface/State/index.ts
Labels: bug

#338 233 Dream List Name Position fix
  zamong/src/components/Dream/styles.ts
Labels: enhancement

#343 313 interpretation of a dream main page Functional implementation.
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/styles.ts
  zamong/src/models/dto/response/InterpretationListResponse.ts
  zamong/src/models/dto/response/defaultResponse.ts
  zamong/src/models/dto/response/sellDreamDetailResponse.ts
  zamong/src/utils/api/DreamInterpretationMain/index.ts
Labels: enhancement

#348 344 change response use default response
  zamong/src/models/dto/response/diaryWriteResponse.ts
  zamong/src/models/dto/response/dreamDetailResponse.ts
  zamong/src/models/dto/response/dreamListResponse.ts
  zamong/src/models/dto/response/followingsResponse.ts
  zamong/src/models/dto/response/profileResponse.ts
  zamong/src/models/dto/response/sellDreamDetailResponse.ts
  zamong/src/models/dto/response/shareDreamResponse.ts
Labels: enhancement

#346 345 header link and hover color
  zamong/src/assets/icons/book.svg
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
  zamong/src/components/Header/LoginSkeleton/LoginSkeleton.tsx
Labels: enhancement

#349 347 fix filter tag click bug
  zamong/src/components/Header/Filter/FilterContent/FilterContent.tsx
Labels: bug

#350 261 when another place click, Picker Modal become close
  zamong/src/components/DiaryWrite/component/Picker/Modal/Modal.tsx
  zamong/src/components/DiaryWrite/component/Picker/PickerColunm/PickerColumn.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
Labels: enhancement

#351 317 diary write last save time bug & type is empty but can post bug
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/components/DiaryWrite/component/ElapsedTime/ElapsedTime.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Content/Content.tsx
  zamong/src/components/DiaryWrite/component/Properties/Accordion/AccordionMenus/DreamType/Header/Header.tsx
  zamong/src/components/DiaryWrite/component/Properties/Selecter/DreamQuality/ItemContent/ItemContent.tsx
  zamong/src/components/Header/LoginComponent/LoginComponent.tsx
Labels: bug

#354 316 fix Temporary save
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
Labels: enhancement

#353 334 Profile Button style 수정
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Account/style.ts
Labels: enhancement

#357 315 change logo
  zamong/src/assets/logo/logo.svg
  zamong/src/components/Header/Header.tsx
Labels: enhancement

#356 355 font로 체인지
  zamong/src/components/Profile/Account/style.ts
Labels: enhancement

#359 333 AnotherProfile FollowBtn 위치
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/Profile/AnotherUser/styles.ts
  zamong/src/components/Profile/Follow/FollowContent.tsx
Labels: enhancement

#361 360 add Footer Margin
  zamong/src/components/Footer/Footer.tsx
  zamong/src/components/Footer/styles.ts
Labels: enhancement

#365 342 Fix Detail Comment
  zamong/src/assets/icons/OnRecommend.svg
  zamong/src/assets/icons/Recommend.svg
  zamong/src/assets/index.ts
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/components/DiaryDetail/Comment/styles.ts
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/DiaryDetail/Posting/styles.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#376 364 add favicon
  zamong/public/favicon.ico
  zamong/public/index.html
Labels: enhancement

#368 323 fix sell card component
  zamong/src/components/CardDream/SellingDream/SellingDream.tsx
  zamong/src/components/CardDream/SellingDream/styles.ts
  zamong/src/components/CardDream/index.ts
  zamong/src/components/PageNation/PageNation.tsx
  zamong/src/components/PageNation/styles.ts
  zamong/src/components/Sell/Main/SellMain.tsx
  zamong/src/components/Sell/Main/styles.ts
  zamong/src/components/Sell/SellingDream/SellingDream.tsx
Labels: enhancement

#378 377 When don't have follow or followers
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
Labels: enhancement

#380 321 Sell Dream Detail
  zamong/src/components/SellDetail/Chat/Chat.tsx
  zamong/src/components/SellDetail/Chat/styles.ts
  zamong/src/components/SellDetail/Head/Head.tsx
  zamong/src/components/SellDetail/Head/styles.ts
  zamong/src/components/SellDetail/Posting/Posting.tsx
  zamong/src/components/SellDetail/Posting/styles.ts
  zamong/src/components/SellDetail/SellDatail.tsx
  zamong/src/components/SellDetail/styles.ts
  zamong/src/constance/uri.ts
  zamong/src/container/SellDetail/index.tsx
  zamong/src/container/index.ts
  zamong/src/models/dto/response/sellDreamDetailResponse.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/SellDetail/index.ts
Labels: enhancement

#385 370 interpretation write UI
  zamong/src/components/InterpretationWrite/InterpretationWrite.tsx
  zamong/src/components/InterpretationWrite/components/LucyInput/Content/Content.tsx
  zamong/src/components/InterpretationWrite/components/LucyInput/LucyInput.tsx
  zamong/src/components/InterpretationWrite/components/LucyInput/styles.ts
  zamong/src/components/InterpretationWrite/styles.ts
  zamong/src/container/Chat/index.tsx
  zamong/src/container/InterpretationWrite/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
Labels: enhancement

#386 366 Comment Profile
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#387 306 Search api
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
  zamong/src/components/Search/Dream/Dream.tsx
  zamong/src/components/Search/SearchPage.tsx
  zamong/src/components/Search/style.ts
  zamong/src/constance/uri.ts
  zamong/src/container/Search/index.tsx
  zamong/src/models/dto/response/SearchResponse.ts
  zamong/src/utils/api/Search/index.ts
Labels: enhancement

#388 371 interpretation write API
  zamong/src/models/dto/request/postInterpretationRequest.ts
  zamong/src/models/dto/response/interpretationDetailResponse.ts
  zamong/src/utils/api/InterpretationWrite/index.ts
Labels: enhancement

#389 382 Dream Recommend
  zamong/src/components/DiaryDetail/DiaryDetail.tsx
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/constance/uri.ts
  zamong/src/models/dto/response/dreamDetailResponse.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#390 373 Account Secession API
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#391 372 realize interpretation write fuction
  zamong/src/components/InterpretationWrite/InterpretationWrite.tsx
  zamong/src/container/InterpretationWrite/index.tsx
  zamong/src/models/dto/request/postInterpretationRequest.ts
  zamong/src/models/dto/response/interpretationDetailResponse.ts
  zamong/src/utils/api/InterpretationWrite/index.ts
Labels: enhancement

#394 392 header serach function
  zamong/src/components/Header/Header.tsx
Labels: enhancement

#395 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/styles.ts
  zamong/src/interface/Chat/index.ts
Labels: enhancement

#397 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
Labels: enhancement

#398 393 Auth Animation
  zamong/src/components/Common/auth/AuthBackground.tsx
  zamong/src/components/Common/auth/styles.ts
Labels: enhancement

#404 383 Interpretation Dream Detail
  zamong/src/assets/icons/offCheck.svg
  zamong/src/assets/icons/onCheck.svg
  zamong/src/assets/index.ts
  zamong/src/components/InterpretationDetail/Comment/Comment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/AdoptComment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/styles.ts
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/ReplyComment/ReplyComment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/ReplyComment/styles.ts
  zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts
  zamong/src/components/InterpretationDetail/Comment/styles.ts
  zamong/src/components/InterpretationDetail/Head/Head.tsx
  zamong/src/components/InterpretationDetail/Head/styles.ts
  zamong/src/components/InterpretationDetail/InterpretationDetail.tsx
  zamong/src/components/InterpretationDetail/Posting/Posting.tsx
  zamong/src/components/InterpretationDetail/Posting/styles.ts
  zamong/src/components/InterpretationDetail/styles.ts
  zamong/src/constance/uri.ts
  zamong/src/container/InterpretationDetail/index.tsx
  zamong/src/container/index.ts
  zamong/src/models/dto/response/InterpretationDetail.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/DreamDetail/index.ts
  zamong/src/utils/api/InterpretationDetail/index.ts
Labels: enhancement

#405 400 add lucy on interpretation list response
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/models/dto/response/InterpretationListResponse.ts
Labels: enhancement

#402 399 change link on card and list
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
Labels: enhancement

#412 408 fix detail not enterd
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/InterpretationDetail/Posting/Posting.tsx
  zamong/src/components/SellDetail/Posting/Posting.tsx
Labels: bug

#413 407 Interpretation Answerer
  zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/styles.ts
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts
Labels: enhancement

#411 401 auto fill background color change
  zamong/src/style/globalStyle.ts
Labels: enhancement

#414 406 Interpretation Render
  zamong/src/components/InterpretationDetail/Comment/CommentBox/AdoptComment/AdoptComment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
Labels: enhancement

#417 403 interpretation write now lucy count
  zamong/src/components/InterpretationWrite/InterpretationWrite.tsx
  zamong/src/components/InterpretationWrite/components/LucyInput/Content/Content.tsx
Labels: enhancement

#416 396 Search Fix
  zamong/src/components/Search/Dream/Dream.tsx
  zamong/src/components/Search/Dream/style.ts
  zamong/src/components/Search/SearchPage.tsx
  zamong/src/components/Search/style.ts
Labels: enhancement

#418 375 delete save when on post
  zamong/src/components/DiaryWrite/DiaryWrite.tsx
Labels: enhancement

#421 419 fix main page nav
  zamong/src/components/MainPage/MainPage.tsx
Labels: bug

#422 420 Diary Page Refactor
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
Labels: enhancement

#423 374 change Footer
  zamong/src/components/Footer/Footer.tsx
  zamong/src/components/Footer/styles.ts
Labels: enhancement

#426 339 Optimization of pictures
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Header/Header.tsx
  zamong/src/components/Header/styles.ts
Labels: enhancement

#429 240 when more page add
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx
  zamong/src/components/MainPage/DreamList/DreamList.tsx
Labels: enhancement

#431 430 fix gap on chat request
  zamong/src/components/SellDetail/Chat/Chat.tsx
  zamong/src/components/SellDetail/Chat/styles.ts
Labels: enhancement

#428 427 fix page nation component
  zamong/src/components/PageNation/PageNation.tsx
Labels: bug, enhancement

#432 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/styles.ts
Labels: enhancement

#433 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
Labels: enhancement

#434 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/styles.ts
  zamong/src/interface/Chat/index.ts
  zamong/src/utils/api/Chat/index.ts
Labels: enhancement

#441 308 Find Password api
  zamong/src/components/ChangePassword/ChangePassword.tsx
  zamong/src/components/ChangePassword/styles.ts
  zamong/src/components/FindPassword/Change/Change.tsx
  zamong/src/components/FindPassword/Find/Find.tsx
  zamong/src/components/FindPassword/FindPassword.tsx
  zamong/src/components/FindPassword/styles.ts
  zamong/src/components/Login/Login.tsx
  zamong/src/components/SignUp/SignUpND/SignUp.tsx
  zamong/src/constance/uri.ts
  zamong/src/container/ChangePassword/index.tsx
  zamong/src/container/index.ts
  zamong/src/route/MainRouter.tsx
  zamong/src/utils/api/FIndPassword/index.ts
Labels: enhancement

#440 439 add sign up link on non login hello message
  zamong/src/components/MainPage/MainPage.tsx
Labels: enhancement

#438 437 apply skeleton
  zamong/src/components/DreamInterpretationMain/DreamInterpretationList/DreamInterpretationList.tsx
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamDiaryList/MyDreamDiaryList/MyDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamList/DreamList.tsx
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/MainPage/FollowList/styles.ts
  zamong/src/constance/defaultImageList.ts
Labels: enhancement

#443 442 Folder Name Error
  zamong/src/components/ChangePassword/ChangePassword.tsx
  zamong/src/components/FindPassword/FindPassword.tsx
Labels: bug

#445 444 Sell Dream Style
  zamong/src/components/SellDetail/Chat/styles.ts
Labels: enhancement

#448 282 Chat Implementation
  zamong/src/components/Chat/Chat.tsx
  zamong/src/components/Chat/ChatRoom/ChatRoom.tsx
  zamong/src/components/Chat/styles.ts
Labels: enhancement

#450 446 Profile Link
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Head/Head.tsx
  zamong/src/components/InterpretationDetail/Head/styles.ts
  zamong/src/components/SellDetail/Chat/Chat.tsx
  zamong/src/components/SellDetail/Chat/styles.ts
  zamong/src/components/SellDetail/Head/Head.tsx
  zamong/src/components/SellDetail/Head/styles.ts
Labels: enhancement

#452 451 Modify comment
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/DiaryDetail.tsx
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/InterpretationDetail/Comment/Comment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Head/Head.tsx
Labels: enhancement

#455 449 change profile style
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Account/style.ts
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/Profile/AnotherUser/styles.ts
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/components/User/FollowUser/FollowUser.tsx
  zamong/src/components/User/FollowerUser/FollowerUser.tsx
  zamong/src/components/User/styles.ts
  zamong/src/components/UserSkeleton/UserSkeleton.tsx
  zamong/src/components/UserSkeleton/styles.ts
  zamong/src/models/dto/response/profileResponse.ts
Labels: enhancement

#465 464 fix folder name error
  zamong/src/container/index.ts
  zamong/src/utils/api/FindPassword/index.ts
Labels: bug

#462 461 following list more action
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/MainPage/FollowList/styles.ts
Labels: enhancement

#460 458 profile query string
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/ProfilePage.tsx
Labels: enhancement

#459 457 sign up link in login page
  zamong/src/components/Login/Login.tsx
  zamong/src/components/Login/styles.ts
Labels: enhancement

#469 463 fix map key error
  zamong/src/components/Diary/Calendar/styles.ts
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/Dream/Dream.tsx
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/components/DreamInterpretationMain/DefaultDreamInterpretation/DefaultDreamInterpretation.tsx
  zamong/src/components/InterpretationDetail/Posting/Posting.tsx
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/components/MainPage/DreamList/DreamList.tsx
  zamong/src/components/MainPage/FollowList/FollowList.tsx
  zamong/src/components/MainPage/MainPage.tsx
  zamong/src/components/Search/SearchPage.tsx
  zamong/src/components/Sell/Main/SellMain.tsx
  zamong/src/components/SellDetail/Posting/Posting.tsx
Labels: bug, enhancement

#470 468 Folder Name error
  zamong/src/container/FindPassword/index.tsx
Labels: bug

#471 435 move user profile when click profile image
  zamong/src/components/CardDream/FollowDreamDiary/FollowDreamDiary.tsx
  zamong/src/components/CardDream/SellingDream/SellingDream.tsx
  zamong/src/components/Dream/Dream.tsx
  zamong/src/components/Dream/DreamInterpretation/DreamInterpretation.tsx
  zamong/src/components/MainPage/DreamDiaryList/FollowDreamDiaryList/FollowDreamDiaryList.tsx
  zamong/src/utils/api/Main/index.ts
Labels: enhancement

#472 466 change diary style
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
  zamong/src/components/Diary/DiaryList/styles.ts
Labels: enhancement

#476 466 change diary style
  zamong/src/components/Diary/DiaryList/DiaryList.tsx
Labels: enhancement

#479 288 SellManagement api
  zamong/src/components/CardDream/MySellDreamCard/MySellDreamCard.tsx
  zamong/src/components/CardDream/MySellDreamCard/styles.ts
  zamong/src/components/CardDream/SellingDream/SellingDream.tsx
  zamong/src/components/Sell/SellManagement/DreamContent/DreamContent.tsx
  zamong/src/components/Sell/SellManagement/DreamContent/style.ts
  zamong/src/components/Sell/SellManagement/SellManagement.tsx
  zamong/src/components/Sell/SellManagement/style.ts
  zamong/src/models/dto/response/sellManagementResponse.ts
  zamong/src/utils/api/Sell/Management/index.ts
Labels: enhancement

#480 447 불필요한 console.log & alert 삭제
  zamong/src/components/Background/Background.tsx
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/User/FollowUser/FollowUser.tsx
  zamong/src/components/User/FollowerUser/FollowerUser.tsx
Labels: enhancement

#481 363 Modfiy Pw api
  zamong/src/components/Profile/Account/AccountContent.tsx
  zamong/src/components/Profile/Account/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/utils/api/Profile/index.ts
Labels: enhancement

#483 477 After Delete Move To Previous Page
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/InterpretationDetail/Head/Head.tsx
  zamong/src/components/SellDetail/Chat/Chat.tsx
  zamong/src/components/SellDetail/Head/Head.tsx
Labels: enhancement

#482 474 Anonymous comment
  zamong/src/components/DiaryDetail/Comment/Comment.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/components/DiaryDetail/Comment/styles.ts
  zamong/src/components/InterpretationDetail/Comment/Comment.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts
  zamong/src/components/InterpretationDetail/Comment/styles.ts
  zamong/src/utils/api/DreamDetail/index.ts
Labels: enhancement

#485 484 default image action
  zamong/src/components/DiaryDetail/Posting/Posting.tsx
  zamong/src/components/DiaryDetail/Posting/styles.ts
  zamong/src/constance/defaultImageList.ts
Labels: enhancement

#487 486 can enter profile even thought Anonymous comment
  zamong/src/components/DiaryDetail/Comment/CommentBox/CommentBox.tsx
  zamong/src/components/InterpretationDetail/Comment/CommentBox/CommentBox.tsx
Labels: enhancement

#489 486 can enter profile even thought Anonymous comment
  zamong/src/components/DiaryDetail/Head/Head.tsx
  zamong/src/components/InterpretationDetail/Head/Head.tsx
  zamong/src/components/SellDetail/Head/Head.tsx
Labels: bug

#488 484 default image action
  zamong/src/components/InterpretationDetail/Posting/Posting.tsx
  zamong/src/components/InterpretationDetail/Posting/styles.ts
  zamong/src/components/SellDetail/Posting/Posting.tsx
  zamong/src/components/SellDetail/Posting/styles.ts
Labels: enhancement

#491 490 zamong.org auto distribution settings
  .github/workflows/zamong.yml
Labels: Distribution

#492 490 zamong.org auto distribution settings
  .github/workflows/zamong.yml
Labels: Distribution

#493 490 zamong.org auto distribution settings
  .github/workflows/zamong.yml
Labels: Distribution

#494 490 zamong.org auto distribution settings
  .github/workflows/zamong.yml
Labels: Distribution

#500 499 add Badge in profile
  zamong/src/assets/Badge/Bronze.svg
  zamong/src/assets/Badge/Diamond.svg
  zamong/src/assets/Badge/Gold.svg
  zamong/src/assets/Badge/Master.svg
  zamong/src/assets/Badge/Silver.svg
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/Profile/AnotherUser/styles.ts
  zamong/src/components/Profile/Badge/Badge.tsx
  zamong/src/components/Profile/Badge/styles.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Profile/style.ts
  zamong/src/models/dto/response/profileResponse.ts
Labels: enhancement

#502 454 profile follower and follwing list always size is 4
  zamong/src/components/Profile/AnotherUser/AnotherProfilePage.tsx
  zamong/src/components/Profile/Follow/FollowContent.tsx
  zamong/src/components/Profile/Follow/style.ts
  zamong/src/components/Profile/Follower/FollowerContent.tsx
  zamong/src/components/Profile/Follower/style.ts
  zamong/src/components/Profile/ProfilePage.tsx
  zamong/src/components/Search/SearchPage.tsx
  zamong/src/components/User/styles.ts
  zamong/src/models/dto/request/followListRequest.ts
  zamong/src/models/dto/response/followerResponse.ts
  zamong/src/utils/api/Profile/index.ts
Labels: bug

#504 503 오류
  zamong/src/components/Search/SearchPage.tsx
Labels: bug

#507 505 Comment Profile
  zamong/src/components/DiaryDetail/Comment/CommentBox/styles.ts
  zamong/src/components/DiaryDetail/Head/styles.ts
  zamong/src/components/InterpretationDetail/Comment/CommentBox/styles.ts
  zamong/src/components/InterpretationDetail/Head/styles.ts
  zamong/src/components/SellDetail/Head/styles.ts
Labels: bug

#508 506 Profile Picture
  zamong/src/components/Profile/style.ts
Labels: bug
